### PR TITLE
Add Translate

### LINKED ISSUE #5: Google Translate Planned?
Just wondering if Google Translate is planned for this. This library is looking awesome so far, but there's only one Translate API wrapper right now and it's 4 years old.

### PR DESCRIPTION
**Pull request by watzon**
Figured I may as well PR this myself. This adds support for the Google Translate API. I'm sure there are some things that could be improved upon, but I tried to follow the general code style as I saw it.

Closes #5

### CODE REVIEW

**Comment by watzon** [comment]
As it turns out, some of the methods were supposed to be POST requests with a JSON body, but I was trying to do URL parameters. For some reason it still worked for small queries even using GET, but it broke with larger, more complicated translations.

**Comment by stakach** [comment]
Code looks great! Thanks for contributing.
Would it be possible to add a few specs?

Mocking out the requests is pretty simple, something like this:
https://github.com/PlaceOS/google/blob/master/spec/calendar/calendar_spec.cr#L160

Makes ongoing maintenance simpler as otherwise we might miss something in the future

**Comment by watzon** [comment]
Yeah I was thinking about that. Should be doable.

**Comment by watzon** [comment]
Ok specs have been added and are passing. Lmk if there's anything else you need.

**Comment by stakach** [comment]
Thanks!

**Comment by stakach** [comment]
released as v2.2.0

**Pull request merged**
